services:
  - type: web
    name: celectical-shop
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
    staticSites:
      - name: frontend
        buildCommand: "echo 'Frontend built'"
        publishPath: "/frontend"